/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Space/Alien.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Alien(props) {
  const { nodes, materials } = useGLTF('./models/Space/Alien.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Alien_mesh.geometry} material={materials.lambert2SG} />
      {/* <mesh geometry={nodes.Alien_mesh.geometry} >
        <meshStandardMaterial color="green" />
      </mesh> */}
    </group>
  )
}

useGLTF.preload('./models/Space/Alien.glb')
