/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Astronaut/Astronaut.glb 
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";
import React, { useRef } from "react";
import { fadeOnBeforeCompile } from "../utils/fadeMaterial";


const HELIX_SPEED = 0.3;


export function Astronaut({ sceneOpacity, ...props }) {
  const { nodes, materials } = useGLTF('./models/Space/Astronaut.glb')

  const helix = useRef();

  useFrame((_state, delta) => {
    helix.current.rotation.z += delta * HELIX_SPEED;
  });

  const materialRef = useRef([]);

  useFrame(() => {
    // materialRef.current.opacity = sceneOpacity.current;
    materialRef.current.forEach((material) => {
      if (material) {
        material.opacity = sceneOpacity.current;
      }
    })
  });
  return (
    <group {...props} dispose={null} ref={helix}>
      {Object.keys(nodes).map((key, index) => {
        if (nodes[key].isMesh) {
          return (
            <mesh key={key} geometry={nodes[key].geometry}>
              <meshStandardMaterial
                ref={(el) => (materialRef.current[index] = el)} // Store ref for each material
                onBeforeCompile={fadeOnBeforeCompile}
                envMapIntensity={2}
                transparent
              // opacity={sceneOpacity.current}
              />
            </mesh>
          );
        }
        return null;
      })}
    </group>
    /*
    <group {...props} dispose={null} ref={helix}>
      <mesh geometry={nodes.group1167641645.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1707873932.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1907831520.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group666895494.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1098147410.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group282412729.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group139908371.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1506934965.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1753656922.geometry} material={materials.mat5} />
      <mesh geometry={nodes.group549386394.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group1621723427.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group332686008.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1203591074.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1138436095.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group505957385.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group279303741.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group2056735301.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group1015039822.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group276692338.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group1437890092.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group790332696.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group654761556.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1852607879.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group2057329393.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group2143627782.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group1564631837.geometry} material={materials.mat5} />
      <mesh geometry={nodes.group925645544.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group734772326.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group1934812181.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group2060591166.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group1167954657.geometry} material={materials.mat5} />
      <mesh geometry={nodes.group1042580755.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group1572698854.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group104451256.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1188494358.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1217407763.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group828877529.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group1423311402.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group762855551.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1514672780.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1310595050.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1369611446.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group450518597.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group745840913.geometry} material={materials.mat5} />
      <mesh geometry={nodes.group42438703.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group503988050.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1602554113.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group887420200.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1440063915.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group247475039.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group456781955.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group724382726.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1277767469.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group954316612.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group989277149.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group797940765.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1808813520.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group255140077.geometry} material={materials.mat5} />
      <mesh geometry={nodes.group524469484.geometry} material={materials.mat5} />
      <mesh geometry={nodes.group279101508.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1596727529.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group2129567275.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group373555577.geometry} material={materials.mat5} />
      <mesh geometry={nodes.group314405485.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group991616414.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1896148415.geometry} material={materials.mat5} />
      <mesh geometry={nodes.group1481515652.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group781958242.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1830018461.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1307457211.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group638132290.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group1181203045.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group157177855.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group1453338879.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group282641779.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group1884950168.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group657325723.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1943308988.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group530823911.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group1585682906.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group986243464.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group456711604.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group1614853819.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group332540088.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group1163682321.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group1921399779.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group584895319.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group1679735649.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group11481041.geometry} material={materials.mat16} />
    </group>
    */
  )
}

useGLTF.preload('./models/Space/Astronaut.glb')
