/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/airplane/Jet.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Jet(props) {
  const { nodes, materials } = useGLTF('./models/airplane/Jet.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Jet.geometry} material={materials.Mat} />
    </group>
  )
}

useGLTF.preload('./models/airplane/Jet.glb')
