/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Space/Comet.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Comet(props) {
  const { nodes, materials } = useGLTF('./models/Space/Comet.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node.geometry} material={materials.Comet_mat} />
    </group>
  )
}

useGLTF.preload('./ models / Space / Comet.glb')
