/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/airplane/spaceship.glb 
*/
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import React, { useRef } from "react";

const HELIX_SPEED = 6;

export function Spaceship(props) {
  const { nodes, materials } = useGLTF("../../public/models/airplane/spaceship.glb")

  // const helix = useRef();

  // useFrame((_state, delta) => {
  //   helix.current.rotation.x += delta * HELIX_SPEED;
  // });
  return (
    <group
      {...props} dispose={null}>
      <mesh
        // ref={helix}
        // position={[1.09, 0.23, 0]}
        geometry={nodes.Lo_poly_Spaceship_01_by_Liz_Reddington_1.geometry}
        material={materials.lambert2SG} />
      <mesh
        geometry={nodes.Lo_poly_Spaceship_01_by_Liz_Reddington_1_1.geometry}
        material={materials.lambert4SG} />
      <mesh
        geometry={nodes.Lo_poly_Spaceship_01_by_Liz_Reddington_1_2.geometry}
        material={materials.lambert3SG} />
    </group>
  )
}

useGLTF.preload("../../public/models/airplane/spaceship.glb")
