# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - job-seeker

on:
  push:
    branches:
      - candidate_rs
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        working-directory: backend/recommendation
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        working-directory: backend/recommendation
        run: pip install -r requirements.txt
        
      # Optional: Add a step here to run tests (e.g., pytest) if needed

      - name: Zip artifact for deployment
        working-directory: backend/recommendation
        run: |
          # Zip contents of the FastAPI project, excluding the virtual environment and other unnecessary directories.
          zip -r ../../release.zip . -x "venv/*" "*__pycache__*"
        
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write    # Required for requesting the JWT
      contents: read     # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_284BF58057184E00BB0BDF551FFF45C2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_00C0ADD565D94DA5B4A1C89B526B0493 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5E9EC12A932341CBA542CDCABD717994 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'job-seeker'
          slot-name: 'Production'
