# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - job-seeker

on:
  push:
    branches:
      - candidate_rs
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        working-directory: backend/recommendation
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        working-directory: backend/recommendation
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip only backend project for deployment
        run: |
          cd backend/recommendation
          zip -r ../../release.zip . -x "*__pycache__*" "*.venv*" "*.git*" "*.md"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_40BCBE6BE9D14AA9BD4B36775DE68854 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_98D3B95273A5402EA16AF797A84F00DE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B9D2670B58F2437793CEED255E0EF277 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'job-seeker'
          slot-name: 'Production'
          
# name: Build and deploy FastAPI app to Azure Web App - job-seeker

# on:
#   push:
#     branches:
#       - candidate_rs
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read

#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.10'

#       - name: Install dependencies from backend/recommendation
#         run: |
#           pip install -r backend/recommendation/requirements.txt

#       - name: Zip backend/recommendation folder
#         run: |
#           cd backend/recommendation
#           zip -r ../../release.zip . -x "*__pycache__*" "*.venv*" "*.git*" "*.md"

#       - name: Upload artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: fastapi-app
#           path: release.zip

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     environment:
#       name: 'Production'
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

#     steps:
#       - name: Download artifact
#         uses: actions/download-artifact@v4
#         with:
#           name: fastapi-app

#       - name: Unzip artifact
#         run: unzip release.zip -d deployment

#       - name: Login to Azure
#         uses: azure/login@v2
#         with:
#           client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_40BCBE6BE9D14AA9BD4B36775DE68854 }}
#           tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_98D3B95273A5402EA16AF797A84F00DE }}
#           subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B9D2670B58F2437793CEED255E0EF277 }}

#       - name: Deploy to Azure Web App
#         uses: azure/webapps-deploy@v3
#         id: deploy-to-webapp
#         with:
#           app-name: 'job-seeker'
#           slot-name: 'Production'
#           package: deployment
